/* tslint:disable */
/* eslint-disable */
/**
 * Learner Management API
 * Learner profile and learning data management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BulkImportRequest,
  BulkImportResponse,
} from '../models/index';
import {
    BulkImportRequestFromJSON,
    BulkImportRequestToJSON,
    BulkImportResponseFromJSON,
    BulkImportResponseToJSON,
} from '../models/index';

export interface BulkImportLearnersRequest {
    bulkImportRequest: BulkImportRequest;
}

/**
 * 
 */
export class BulkOperationsApi extends runtime.BaseAPI {

    /**
     * Bulk import learners
     */
    async bulkImportLearnersRaw(requestParameters: BulkImportLearnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkImportResponse>> {
        if (requestParameters['bulkImportRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkImportRequest',
                'Required parameter "bulkImportRequest" was null or undefined when calling bulkImportLearners().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bulk-import`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BulkImportRequestToJSON(requestParameters['bulkImportRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BulkImportResponseFromJSON(jsonValue));
    }

    /**
     * Bulk import learners
     */
    async bulkImportLearners(requestParameters: BulkImportLearnersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkImportResponse> {
        const response = await this.bulkImportLearnersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
