"""
Payments & Billing API

Subscription billing and payment processing service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.discount import Discount


class TestDiscount(unittest.TestCase):
    """Discount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Discount:
        """Test Discount
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Discount`
        """
        model = Discount()
        if include_optional:
            return Discount(
                coupon_id = 'coup_123e4567-e89b-12d3-a456-426614174000',
                coupon_code = 'WELCOME20',
                discount_type = 'percent',
                discount_value = 20.0
            )
        else:
            return Discount(
        )
        """

    def testDiscount(self):
        """Test Discount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
