"""
Payments & Billing API

Subscription billing and payment processing service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_subscription(self) -> None:
        """Test case for cancel_subscription

        Cancel subscription
        """
        pass

    def test_create_subscription(self) -> None:
        """Test case for create_subscription

        Create new subscription
        """
        pass

    def test_get_subscription(self) -> None:
        """Test case for get_subscription

        Get subscription by ID
        """
        pass

    def test_list_subscriptions(self) -> None:
        """Test case for list_subscriptions

        List subscriptions
        """
        pass

    def test_update_subscription(self) -> None:
        """Test case for update_subscription

        Update subscription
        """
        pass


if __name__ == "__main__":
    unittest.main()
