"""
Payments & Billing API

Subscription billing and payment processing service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.payment_method_bank_account import PaymentMethodBankAccount


class TestPaymentMethodBankAccount(unittest.TestCase):
    """PaymentMethodBankAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodBankAccount:
        """Test PaymentMethodBankAccount
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PaymentMethodBankAccount`
        """
        model = PaymentMethodBankAccount()
        if include_optional:
            return PaymentMethodBankAccount(
                bank_name = 'Chase Bank',
                last4 = '6789',
                account_type = 'checking'
            )
        else:
            return PaymentMethodBankAccount(
        )
        """

    def testPaymentMethodBankAccount(self):
        """Test PaymentMethodBankAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
