# coding: utf-8

"""
    Admin Portal Aggregator API

    Read-only aggregator API for admin dashboard widgets and KPIs

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.team_overview_top_users_inner import TeamOverviewTopUsersInner

class TestTeamOverviewTopUsersInner(unittest.TestCase):
    """TeamOverviewTopUsersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamOverviewTopUsersInner:
        """Test TeamOverviewTopUsersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamOverviewTopUsersInner`
        """
        model = TeamOverviewTopUsersInner()
        if include_optional:
            return TeamOverviewTopUsersInner(
                user_id = '',
                name = 'John Doe',
                email = 'john@example.com',
                role = 'instructor',
                last_active = '2023-12-01T09:15:00Z',
                enrollments = 15
            )
        else:
            return TeamOverviewTopUsersInner(
        )
        """

    def testTeamOverviewTopUsersInner(self):
        """Test TeamOverviewTopUsersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
