"""
Admin Portal Aggregator API

Read-only aggregator API for admin dashboard widgets and KPIs

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.namespaces_overview_status_counts import NamespacesOverviewStatusCounts


class TestNamespacesOverviewStatusCounts(unittest.TestCase):
    """NamespacesOverviewStatusCounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NamespacesOverviewStatusCounts:
        """Test NamespacesOverviewStatusCounts
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `NamespacesOverviewStatusCounts`
        """
        model = NamespacesOverviewStatusCounts()
        if include_optional:
            return NamespacesOverviewStatusCounts(
                active = 112,
                inactive = 18,
                initializing = 3,
                error = 2
            )
        else:
            return NamespacesOverviewStatusCounts(
                active = 112,
                inactive = 18,
                initializing = 3,
                error = 2,
        )
        """

    def testNamespacesOverviewStatusCounts(self):
        """Test NamespacesOverviewStatusCounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
