# coding: utf-8

"""
    Admin Portal Aggregator API

    Read-only aggregator API for admin dashboard widgets and KPIs

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.api.subscription_api import SubscriptionApi


class TestSubscriptionApi(unittest.TestCase):
    """SubscriptionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionApi()

    def tearDown(self) -> None:
        pass

    def test_get_tenant_subscription(self) -> None:
        """Test case for get_tenant_subscription

        Get tenant subscription details
        """
        pass


if __name__ == '__main__':
    unittest.main()
