# coding: utf-8

"""
    Admin Portal Aggregator API

    Read-only aggregator API for admin dashboard widgets and KPIs

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.billing_history_webhooks_status import BillingHistoryWebhooksStatus

class TestBillingHistoryWebhooksStatus(unittest.TestCase):
    """BillingHistoryWebhooksStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingHistoryWebhooksStatus:
        """Test BillingHistoryWebhooksStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingHistoryWebhooksStatus`
        """
        model = BillingHistoryWebhooksStatus()
        if include_optional:
            return BillingHistoryWebhooksStatus(
                is_configured = True,
                last_success = '2023-12-01T10:30:00Z',
                failure_count = 0,
                endpoint = 'https://api.customer.com/aivo-webhooks'
            )
        else:
            return BillingHistoryWebhooksStatus(
                is_configured = True,
                last_success = '2023-12-01T10:30:00Z',
                failure_count = 0,
        )
        """

    def testBillingHistoryWebhooksStatus(self):
        """Test BillingHistoryWebhooksStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
