# coding: utf-8

"""
    Admin Portal Aggregator API

    Read-only aggregator API for admin dashboard widgets and KPIs

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.team_overview_pending_invites import TeamOverviewPendingInvites

class TestTeamOverviewPendingInvites(unittest.TestCase):
    """TeamOverviewPendingInvites unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamOverviewPendingInvites:
        """Test TeamOverviewPendingInvites
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamOverviewPendingInvites`
        """
        model = TeamOverviewPendingInvites()
        if include_optional:
            return TeamOverviewPendingInvites(
                total = 5,
                by_role = aivo_sdk.models.team_overview_pending_invites_by_role.TeamOverview_pendingInvites_byRole(
                    tenant_admin = 0, 
                    instructor = 2, 
                    learner = 3, ),
                oldest_invite = '2023-11-15T09:00:00Z'
            )
        else:
            return TeamOverviewPendingInvites(
                total = 5,
                by_role = aivo_sdk.models.team_overview_pending_invites_by_role.TeamOverview_pendingInvites_byRole(
                    tenant_admin = 0, 
                    instructor = 2, 
                    learner = 3, ),
        )
        """

    def testTeamOverviewPendingInvites(self):
        """Test TeamOverviewPendingInvites"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
