# coding: utf-8

"""
    Learning Orchestrator API

    Course orchestration and learning path management service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aivo_sdk.models.create_learning_path_request_courses_inner import CreateLearningPathRequestCoursesInner
from typing import Optional, Set
from typing_extensions import Self

class CreateLearningPathRequest(BaseModel):
    """
    CreateLearningPathRequest
    """ # noqa: E501
    title: Annotated[str, Field(min_length=3, strict=True, max_length=200)]
    description: Annotated[str, Field(min_length=10, strict=True, max_length=2000)]
    category: StrictStr
    difficulty: Optional[StrictStr] = None
    thumbnail_url: Optional[StrictStr] = Field(default=None, alias="thumbnailUrl")
    tags: Optional[Annotated[List[StrictStr], Field(max_length=10)]] = None
    courses: Annotated[List[CreateLearningPathRequestCoursesInner], Field(min_length=1)]
    __properties: ClassVar[List[str]] = ["title", "description", "category", "difficulty", "thumbnailUrl", "tags", "courses"]

    @field_validator('difficulty')
    def difficulty_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['beginner', 'intermediate', 'advanced']):
            raise ValueError("must be one of enum values ('beginner', 'intermediate', 'advanced')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateLearningPathRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in courses (list)
        _items = []
        if self.courses:
            for _item_courses in self.courses:
                if _item_courses:
                    _items.append(_item_courses.to_dict())
            _dict['courses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateLearningPathRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "category": obj.get("category"),
            "difficulty": obj.get("difficulty"),
            "thumbnailUrl": obj.get("thumbnailUrl"),
            "tags": obj.get("tags"),
            "courses": [CreateLearningPathRequestCoursesInner.from_dict(_item) for _item in obj["courses"]] if obj.get("courses") is not None else None
        })
        return _obj


