/* tslint:disable */
/* eslint-disable */
/**
 * Learner Management API
 * Learner profile and learning data management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateLearnerRequest } from './CreateLearnerRequest';
import {
    CreateLearnerRequestFromJSON,
    CreateLearnerRequestFromJSONTyped,
    CreateLearnerRequestToJSON,
    CreateLearnerRequestToJSONTyped,
} from './CreateLearnerRequest';

/**
 * 
 * @export
 * @interface BulkImportRequest
 */
export interface BulkImportRequest {
    /**
     * 
     * @type {string}
     * @memberof BulkImportRequest
     */
    tenantId: string;
    /**
     * 
     * @type {Array<CreateLearnerRequest>}
     * @memberof BulkImportRequest
     */
    learners: Array<CreateLearnerRequest>;
}

/**
 * Check if a given object implements the BulkImportRequest interface.
 */
export function instanceOfBulkImportRequest(value: object): value is BulkImportRequest {
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('learners' in value) || value['learners'] === undefined) return false;
    return true;
}

export function BulkImportRequestFromJSON(json: any): BulkImportRequest {
    return BulkImportRequestFromJSONTyped(json, false);
}

export function BulkImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenantId'],
        'learners': ((json['learners'] as Array<any>).map(CreateLearnerRequestFromJSON)),
    };
}

export function BulkImportRequestToJSON(json: any): BulkImportRequest {
    return BulkImportRequestToJSONTyped(json, false);
}

export function BulkImportRequestToJSONTyped(value?: BulkImportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenantId': value['tenantId'],
        'learners': ((value['learners'] as Array<any>).map(CreateLearnerRequestToJSON)),
    };
}

