/* tslint:disable */
/* eslint-disable */
/**
 * Learner Management API
 * Learner profile and learning data management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LearnerAnalyticsActivityDataInner
 */
export interface LearnerAnalyticsActivityDataInner {
    /**
     * 
     * @type {Date}
     * @memberof LearnerAnalyticsActivityDataInner
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof LearnerAnalyticsActivityDataInner
     */
    minutesLearned?: number;
    /**
     * 
     * @type {number}
     * @memberof LearnerAnalyticsActivityDataInner
     */
    sessionsCount?: number;
}

/**
 * Check if a given object implements the LearnerAnalyticsActivityDataInner interface.
 */
export function instanceOfLearnerAnalyticsActivityDataInner(value: object): value is LearnerAnalyticsActivityDataInner {
    return true;
}

export function LearnerAnalyticsActivityDataInnerFromJSON(json: any): LearnerAnalyticsActivityDataInner {
    return LearnerAnalyticsActivityDataInnerFromJSONTyped(json, false);
}

export function LearnerAnalyticsActivityDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearnerAnalyticsActivityDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'minutesLearned': json['minutesLearned'] == null ? undefined : json['minutesLearned'],
        'sessionsCount': json['sessionsCount'] == null ? undefined : json['sessionsCount'],
    };
}

export function LearnerAnalyticsActivityDataInnerToJSON(json: any): LearnerAnalyticsActivityDataInner {
    return LearnerAnalyticsActivityDataInnerToJSONTyped(json, false);
}

export function LearnerAnalyticsActivityDataInnerToJSONTyped(value?: LearnerAnalyticsActivityDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'minutesLearned': value['minutesLearned'],
        'sessionsCount': value['sessionsCount'],
    };
}

