/* tslint:disable */
/* eslint-disable */
/**
 * Learner Management API
 * Learner profile and learning data management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LearnerProfileSkillsInner
 */
export interface LearnerProfileSkillsInner {
    /**
     * 
     * @type {string}
     * @memberof LearnerProfileSkillsInner
     */
    skillId?: string;
    /**
     * 
     * @type {string}
     * @memberof LearnerProfileSkillsInner
     */
    skillName?: string;
    /**
     * 
     * @type {string}
     * @memberof LearnerProfileSkillsInner
     */
    level?: LearnerProfileSkillsInnerLevelEnum;
    /**
     * 
     * @type {Date}
     * @memberof LearnerProfileSkillsInner
     */
    verifiedAt?: Date;
}


/**
 * @export
 */
export const LearnerProfileSkillsInnerLevelEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced',
    Expert: 'expert'
} as const;
export type LearnerProfileSkillsInnerLevelEnum = typeof LearnerProfileSkillsInnerLevelEnum[keyof typeof LearnerProfileSkillsInnerLevelEnum];


/**
 * Check if a given object implements the LearnerProfileSkillsInner interface.
 */
export function instanceOfLearnerProfileSkillsInner(value: object): value is LearnerProfileSkillsInner {
    return true;
}

export function LearnerProfileSkillsInnerFromJSON(json: any): LearnerProfileSkillsInner {
    return LearnerProfileSkillsInnerFromJSONTyped(json, false);
}

export function LearnerProfileSkillsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearnerProfileSkillsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'skillId': json['skillId'] == null ? undefined : json['skillId'],
        'skillName': json['skillName'] == null ? undefined : json['skillName'],
        'level': json['level'] == null ? undefined : json['level'],
        'verifiedAt': json['verifiedAt'] == null ? undefined : (new Date(json['verifiedAt'])),
    };
}

export function LearnerProfileSkillsInnerToJSON(json: any): LearnerProfileSkillsInner {
    return LearnerProfileSkillsInnerToJSONTyped(json, false);
}

export function LearnerProfileSkillsInnerToJSONTyped(value?: LearnerProfileSkillsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skillId': value['skillId'],
        'skillName': value['skillName'],
        'level': value['level'],
        'verifiedAt': value['verifiedAt'] == null ? undefined : ((value['verifiedAt']).toISOString()),
    };
}

