# coding: utf-8

"""
    Enrollment Management API

    Learner enrollment and course assignment service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.api.progress_api import ProgressApi


class TestProgressApi(unittest.TestCase):
    """ProgressApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProgressApi()

    def tearDown(self) -> None:
        pass

    def test_get_enrollment_progress(self) -> None:
        """Test case for get_enrollment_progress

        Get enrollment progress
        """
        pass

    def test_update_enrollment_progress(self) -> None:
        """Test case for update_enrollment_progress

        Update enrollment progress
        """
        pass


if __name__ == '__main__':
    unittest.main()
