# coding: utf-8

"""
    Enrollment Management API

    Learner enrollment and course assignment service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.api.bulk_operations_api import BulkOperationsApi


class TestBulkOperationsApi(unittest.TestCase):
    """BulkOperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BulkOperationsApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_enroll(self) -> None:
        """Test case for bulk_enroll

        Bulk enroll learners
        """
        pass


if __name__ == '__main__':
    unittest.main()
