# coding: utf-8

"""
    Tenant Management API

    Multi-tenant organization management service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.tenant import Tenant

class TestTenant(unittest.TestCase):
    """Tenant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Tenant:
        """Test Tenant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tenant`
        """
        model = Tenant()
        if include_optional:
            return Tenant(
                id = '456e7890-e89b-12d3-a456-426614174000',
                name = 'Acme Corporation',
                slug = 'acme-corp',
                description = 'Leading provider of educational content',
                logo = 'https://example.com/logo.png',
                website = 'https://acme.com',
                status = 'active',
                plan = 'professional',
                max_users = 100,
                max_seats = 50,
                trial_ends_at = '2024-01-31T23:59:59Z',
                created_at = '2023-01-01T00:00:00Z',
                updated_at = '2023-12-01T10:30:00Z'
            )
        else:
            return Tenant(
                id = '456e7890-e89b-12d3-a456-426614174000',
                name = 'Acme Corporation',
                slug = 'acme-corp',
                status = 'active',
                plan = 'professional',
                created_at = '2023-01-01T00:00:00Z',
                updated_at = '2023-12-01T10:30:00Z',
        )
        """

    def testTenant(self):
        """Test Tenant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
