"""
Tenant Management API

Multi-tenant organization management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.tenant_settings_features import TenantSettingsFeatures


class TestTenantSettingsFeatures(unittest.TestCase):
    """TenantSettingsFeatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantSettingsFeatures:
        """Test TenantSettingsFeatures
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TenantSettingsFeatures`
        """
        model = TenantSettingsFeatures()
        if include_optional:
            return TenantSettingsFeatures(
                enable_sso = True,
                enable_api = True,
                enable_reporting = True,
                enable_custom_branding = True
            )
        else:
            return TenantSettingsFeatures(
        )
        """

    def testTenantSettingsFeatures(self):
        """Test TenantSettingsFeatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
