"""
Tenant Management API

Multi-tenant organization management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.api.tenants_api import TenantsApi


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantsApi()

    def tearDown(self) -> None:
        pass

    def test_create_tenant(self) -> None:
        """Test case for create_tenant

        Create new tenant
        """
        pass

    def test_delete_tenant(self) -> None:
        """Test case for delete_tenant

        Delete tenant
        """
        pass

    def test_get_tenant(self) -> None:
        """Test case for get_tenant

        Get tenant by ID
        """
        pass

    def test_list_tenants(self) -> None:
        """Test case for list_tenants

        List tenants
        """
        pass

    def test_update_tenant(self) -> None:
        """Test case for update_tenant

        Update tenant
        """
        pass


if __name__ == "__main__":
    unittest.main()
