"""
Tenant Management API

Multi-tenant organization management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.create_tenant_request import CreateTenantRequest


class TestCreateTenantRequest(unittest.TestCase):
    """CreateTenantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTenantRequest:
        """Test CreateTenantRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateTenantRequest`
        """
        model = CreateTenantRequest()
        if include_optional:
            return CreateTenantRequest(
                name = 'Acme Corporation',
                slug = 'acme-corp',
                description = 'Leading provider of educational content',
                website = 'https://acme.com',
                plan = 'professional',
                max_users = 100
            )
        else:
            return CreateTenantRequest(
                name = 'Acme Corporation',
                slug = 'acme-corp',
                plan = 'professional',
        )
        """

    def testCreateTenantRequest(self):
        """Test CreateTenantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
