# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/event_collector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "protos/event_collector.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cprotos/event_collector.proto\x12\x0e\x65ventcollector\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto"\xe7\x01\n\x05\x45vent\x12\x12\n\nlearner_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12)\n\x08metadata\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07version\x18\x08 \x01(\t"W\n\x0c\x45ventRequest\x12%\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x15.eventcollector.Event\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t"w\n\rEventResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x05\x12\x10\n\x08rejected\x18\x02 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x05 \x03(\t\x12\x0f\n\x07success\x18\x06 \x01(\x08"\x0f\n\rHealthRequest"\x9a\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x06\x63hecks\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct"\x12\n\x10ReadinessRequest"\x91\x01\n\x11ReadinessResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07service\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x0c\x64\x65pendencies\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct2\x84\x02\n\x15\x45ventCollectorService\x12P\n\rCollectEvents\x12\x1c.eventcollector.EventRequest\x1a\x1d.eventcollector.EventResponse(\x01\x30\x01\x12G\n\x06Health\x12\x1d.eventcollector.HealthRequest\x1a\x1e.eventcollector.HealthResponse\x12P\n\tReadiness\x12 .eventcollector.ReadinessRequest\x1a!.eventcollector.ReadinessResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "protos.event_collector_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EVENT"]._serialized_start = 112
    _globals["_EVENT"]._serialized_end = 343
    _globals["_EVENTREQUEST"]._serialized_start = 345
    _globals["_EVENTREQUEST"]._serialized_end = 432
    _globals["_EVENTRESPONSE"]._serialized_start = 434
    _globals["_EVENTRESPONSE"]._serialized_end = 553
    _globals["_HEALTHREQUEST"]._serialized_start = 555
    _globals["_HEALTHREQUEST"]._serialized_end = 570
    _globals["_HEALTHRESPONSE"]._serialized_start = 573
    _globals["_HEALTHRESPONSE"]._serialized_end = 727
    _globals["_READINESSREQUEST"]._serialized_start = 729
    _globals["_READINESSREQUEST"]._serialized_end = 747
    _globals["_READINESSRESPONSE"]._serialized_start = 750
    _globals["_READINESSRESPONSE"]._serialized_end = 895
    _globals["_EVENTCOLLECTORSERVICE"]._serialized_start = 898
    _globals["_EVENTCOLLECTORSERVICE"]._serialized_end = 1158
# @@protoc_insertion_point(module_scope)
