# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from protos import event_collector_pb2 as protos_dot_event__collector__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in protos/event_collector_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EventCollectorServiceStub:
    """Event Collector gRPC Service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectEvents = channel.stream_stream(
            "/eventcollector.EventCollectorService/CollectEvents",
            request_serializer=protos_dot_event__collector__pb2.EventRequest.SerializeToString,
            response_deserializer=protos_dot_event__collector__pb2.EventResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/eventcollector.EventCollectorService/Health",
            request_serializer=protos_dot_event__collector__pb2.HealthRequest.SerializeToString,
            response_deserializer=protos_dot_event__collector__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.Readiness = channel.unary_unary(
            "/eventcollector.EventCollectorService/Readiness",
            request_serializer=protos_dot_event__collector__pb2.ReadinessRequest.SerializeToString,
            response_deserializer=protos_dot_event__collector__pb2.ReadinessResponse.FromString,
            _registered_method=True,
        )


class EventCollectorServiceServicer:
    """Event Collector gRPC Service"""

    def CollectEvents(self, request_iterator, context):
        """Stream events to the collector"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Get service health"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Readiness(self, request, context):
        """Get service readiness"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EventCollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CollectEvents": grpc.stream_stream_rpc_method_handler(
            servicer.CollectEvents,
            request_deserializer=protos_dot_event__collector__pb2.EventRequest.FromString,
            response_serializer=protos_dot_event__collector__pb2.EventResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=protos_dot_event__collector__pb2.HealthRequest.FromString,
            response_serializer=protos_dot_event__collector__pb2.HealthResponse.SerializeToString,
        ),
        "Readiness": grpc.unary_unary_rpc_method_handler(
            servicer.Readiness,
            request_deserializer=protos_dot_event__collector__pb2.ReadinessRequest.FromString,
            response_serializer=protos_dot_event__collector__pb2.ReadinessResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "eventcollector.EventCollectorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "eventcollector.EventCollectorService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class EventCollectorService:
    """Event Collector gRPC Service"""

    @staticmethod
    def CollectEvents(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/eventcollector.EventCollectorService/CollectEvents",
            protos_dot_event__collector__pb2.EventRequest.SerializeToString,
            protos_dot_event__collector__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventcollector.EventCollectorService/Health",
            protos_dot_event__collector__pb2.HealthRequest.SerializeToString,
            protos_dot_event__collector__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Readiness(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/eventcollector.EventCollectorService/Readiness",
            protos_dot_event__collector__pb2.ReadinessRequest.SerializeToString,
            protos_dot_event__collector__pb2.ReadinessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
