apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subject-brain-hpa
  namespace: subject-brain
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subject-brain-svc
  minReplicas: 0
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: gpu_queue_depth
        target:
          type: AverageValue
          averageValue: '10'
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
---
apiVersion: v1
kind: Secret
metadata:
  name: subject-brain-secrets
  namespace: subject-brain
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bsb2NhbGhvc3Q6NTQzMi9zdWJqZWN0X2JyYWlu
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8w
  jwt-secret: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subject-brain-models-pvc
  namespace: subject-brain
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
