"""
Admin Portal Aggregator API

Read-only aggregator API for admin dashboard widgets and KPIs

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator


class NamespacesOverviewHealthSummaryCommonIssuesInner(BaseModel):
    """
    NamespacesOverviewHealthSummaryCommonIssuesInner
    """  # noqa: E501

    issue: StrictStr | None = None
    count: StrictInt | None = None
    severity: StrictStr | None = None
    __properties: ClassVar[list[str]] = ["issue", "count", "severity"]

    @field_validator("severity")
    def severity_validate_enum(self, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["low", "medium", "high", "critical"]):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'critical')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of NamespacesOverviewHealthSummaryCommonIssuesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of NamespacesOverviewHealthSummaryCommonIssuesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {"issue": obj.get("issue"), "count": obj.get("count"), "severity": obj.get("severity")}
        )
        return _obj
