"""
Admin Portal Aggregator API

Read-only aggregator API for admin dashboard widgets and KPIs

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field

from aivo_sdk.models.namespaces_overview_health_summary_common_issues_inner import (
    NamespacesOverviewHealthSummaryCommonIssuesInner,
)


class NamespacesOverviewHealthSummary(BaseModel):
    """
    NamespacesOverviewHealthSummary
    """  # noqa: E501

    health_score: (
        Annotated[float, Field(le=100, strict=True, ge=0)]
        | Annotated[int, Field(le=100, strict=True, ge=0)]
        | None
    ) = Field(
        default=None, description="Overall health score of all namespaces", alias="healthScore"
    )
    common_issues: list[NamespacesOverviewHealthSummaryCommonIssuesInner] | None = Field(
        default=None, alias="commonIssues"
    )
    __properties: ClassVar[list[str]] = ["healthScore", "commonIssues"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of NamespacesOverviewHealthSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in common_issues (list)
        _items = []
        if self.common_issues:
            for _item_common_issues in self.common_issues:
                if _item_common_issues:
                    _items.append(_item_common_issues.to_dict())
            _dict["commonIssues"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of NamespacesOverviewHealthSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "healthScore": obj.get("healthScore"),
                "commonIssues": [
                    NamespacesOverviewHealthSummaryCommonIssuesInner.from_dict(_item)
                    for _item in obj["commonIssues"]
                ]
                if obj.get("commonIssues") is not None
                else None,
            }
        )
        return _obj
