"""
Admin Portal Aggregator API

Read-only aggregator API for admin dashboard widgets and KPIs

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictInt

from aivo_sdk.models.team_overview_pending_invites_by_role import TeamOverviewPendingInvitesByRole


class TeamOverviewPendingInvites(BaseModel):
    """
    TeamOverviewPendingInvites
    """  # noqa: E501

    total: StrictInt = Field(description="Total pending invitations")
    by_role: TeamOverviewPendingInvitesByRole = Field(alias="byRole")
    oldest_invite: datetime | None = Field(
        default=None, description="Date of oldest pending invite", alias="oldestInvite"
    )
    __properties: ClassVar[list[str]] = ["total", "byRole", "oldestInvite"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TeamOverviewPendingInvites from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of by_role
        if self.by_role:
            _dict["byRole"] = self.by_role.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TeamOverviewPendingInvites from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "total": obj.get("total"),
                "byRole": TeamOverviewPendingInvitesByRole.from_dict(obj["byRole"])
                if obj.get("byRole") is not None
                else None,
                "oldestInvite": obj.get("oldestInvite"),
            }
        )
        return _obj
