"""
Admin Portal Aggregator API

Read-only aggregator API for admin dashboard widgets and KPIs

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr

from aivo_sdk.models.tenant_summary_enrollment_stats import TenantSummaryEnrollmentStats
from aivo_sdk.models.tenant_summary_learners import TenantSummaryLearners
from aivo_sdk.models.tenant_summary_seats import TenantSummarySeats


class TenantSummary(BaseModel):
    """
    TenantSummary
    """  # noqa: E501

    tenant_id: StrictStr = Field(alias="tenantId")
    learners: TenantSummaryLearners
    seats: TenantSummarySeats
    trial_count: StrictInt = Field(
        description="Number of learners currently in trial", alias="trialCount"
    )
    open_approvals: StrictInt = Field(
        description="Number of pending approval requests", alias="openApprovals"
    )
    enrollment_stats: TenantSummaryEnrollmentStats | None = Field(
        default=None, alias="enrollmentStats"
    )
    last_updated: datetime = Field(
        description="When this summary was last calculated", alias="lastUpdated"
    )
    __properties: ClassVar[list[str]] = [
        "tenantId",
        "learners",
        "seats",
        "trialCount",
        "openApprovals",
        "enrollmentStats",
        "lastUpdated",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TenantSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of learners
        if self.learners:
            _dict["learners"] = self.learners.to_dict()
        # override the default output from pydantic by calling `to_dict()` of seats
        if self.seats:
            _dict["seats"] = self.seats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of enrollment_stats
        if self.enrollment_stats:
            _dict["enrollmentStats"] = self.enrollment_stats.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TenantSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "tenantId": obj.get("tenantId"),
                "learners": TenantSummaryLearners.from_dict(obj["learners"])
                if obj.get("learners") is not None
                else None,
                "seats": TenantSummarySeats.from_dict(obj["seats"])
                if obj.get("seats") is not None
                else None,
                "trialCount": obj.get("trialCount"),
                "openApprovals": obj.get("openApprovals"),
                "enrollmentStats": TenantSummaryEnrollmentStats.from_dict(obj["enrollmentStats"])
                if obj.get("enrollmentStats") is not None
                else None,
                "lastUpdated": obj.get("lastUpdated"),
            }
        )
        return _obj
