/* tslint:disable */
/* eslint-disable */
/**
 * Admin Portal Aggregator API
 * Read-only aggregator API for admin dashboard widgets and KPIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UsageAnalytics,
} from '../models/index';
import {
    UsageAnalyticsFromJSON,
    UsageAnalyticsToJSON,
} from '../models/index';

export interface GetTenantUsageRequest {
    tenantId: string;
    range?: GetTenantUsageRangeEnum;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Get tenant usage analytics
     */
    async getTenantUsageRaw(requestParameters: GetTenantUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsageAnalytics>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling getTenantUsage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/usage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsageAnalyticsFromJSON(jsonValue));
    }

    /**
     * Get tenant usage analytics
     */
    async getTenantUsage(requestParameters: GetTenantUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsageAnalytics> {
        const response = await this.getTenantUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetTenantUsageRangeEnum = {
    _7d: '7d',
    _30d: '30d',
    _90d: '90d',
    _1y: '1y'
} as const;
export type GetTenantUsageRangeEnum = typeof GetTenantUsageRangeEnum[keyof typeof GetTenantUsageRangeEnum];
