/* tslint:disable */
/* eslint-disable */
/**
 * Admin Portal Aggregator API
 * Read-only aggregator API for admin dashboard widgets and KPIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TeamOverview,
} from '../models/index';
import {
    TeamOverviewFromJSON,
    TeamOverviewToJSON,
} from '../models/index';

export interface GetTenantTeamRequest {
    tenantId: string;
}

/**
 * 
 */
export class TeamApi extends runtime.BaseAPI {

    /**
     * Get tenant team overview
     */
    async getTenantTeamRaw(requestParameters: GetTenantTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamOverview>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling getTenantTeam().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/team`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamOverviewFromJSON(jsonValue));
    }

    /**
     * Get tenant team overview
     */
    async getTenantTeam(requestParameters: GetTenantTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamOverview> {
        const response = await this.getTenantTeamRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
