/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseDetailedAllOfRequirements
 */
export interface CourseDetailedAllOfRequirements {
    /**
     * 
     * @type {Array<string>}
     * @memberof CourseDetailedAllOfRequirements
     */
    systemRequirements?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourseDetailedAllOfRequirements
     */
    softwareRequirements?: Array<string>;
}

/**
 * Check if a given object implements the CourseDetailedAllOfRequirements interface.
 */
export function instanceOfCourseDetailedAllOfRequirements(value: object): value is CourseDetailedAllOfRequirements {
    return true;
}

export function CourseDetailedAllOfRequirementsFromJSON(json: any): CourseDetailedAllOfRequirements {
    return CourseDetailedAllOfRequirementsFromJSONTyped(json, false);
}

export function CourseDetailedAllOfRequirementsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseDetailedAllOfRequirements {
    if (json == null) {
        return json;
    }
    return {
        
        'systemRequirements': json['systemRequirements'] == null ? undefined : json['systemRequirements'],
        'softwareRequirements': json['softwareRequirements'] == null ? undefined : json['softwareRequirements'],
    };
}

export function CourseDetailedAllOfRequirementsToJSON(json: any): CourseDetailedAllOfRequirements {
    return CourseDetailedAllOfRequirementsToJSONTyped(json, false);
}

export function CourseDetailedAllOfRequirementsToJSONTyped(value?: CourseDetailedAllOfRequirements | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'systemRequirements': value['systemRequirements'],
        'softwareRequirements': value['softwareRequirements'],
    };
}

