/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateModuleRequest
 */
export interface CreateModuleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    type: CreateModuleRequestTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateModuleRequest
     */
    order: number;
    /**
     * 
     * @type {number}
     * @memberof CreateModuleRequest
     */
    estimatedDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    contentUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModuleRequest
     */
    transcriptUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateModuleRequest
     */
    isOptional?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateModuleRequest
     */
    prerequisites?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateModuleRequest
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const CreateModuleRequestTypeEnum = {
    Video: 'video',
    Text: 'text',
    Interactive: 'interactive',
    Assignment: 'assignment',
    Quiz: 'quiz'
} as const;
export type CreateModuleRequestTypeEnum = typeof CreateModuleRequestTypeEnum[keyof typeof CreateModuleRequestTypeEnum];


/**
 * Check if a given object implements the CreateModuleRequest interface.
 */
export function instanceOfCreateModuleRequest(value: object): value is CreateModuleRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function CreateModuleRequestFromJSON(json: any): CreateModuleRequest {
    return CreateModuleRequestFromJSONTyped(json, false);
}

export function CreateModuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateModuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'],
        'order': json['order'],
        'estimatedDuration': json['estimatedDuration'] == null ? undefined : json['estimatedDuration'],
        'contentUrl': json['contentUrl'] == null ? undefined : json['contentUrl'],
        'transcriptUrl': json['transcriptUrl'] == null ? undefined : json['transcriptUrl'],
        'isOptional': json['isOptional'] == null ? undefined : json['isOptional'],
        'prerequisites': json['prerequisites'] == null ? undefined : json['prerequisites'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateModuleRequestToJSON(json: any): CreateModuleRequest {
    return CreateModuleRequestToJSONTyped(json, false);
}

export function CreateModuleRequestToJSONTyped(value?: CreateModuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'type': value['type'],
        'order': value['order'],
        'estimatedDuration': value['estimatedDuration'],
        'contentUrl': value['contentUrl'],
        'transcriptUrl': value['transcriptUrl'],
        'isOptional': value['isOptional'],
        'prerequisites': value['prerequisites'],
        'metadata': value['metadata'],
    };
}

