/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LearningPath
 */
export interface LearningPath {
    /**
     * 
     * @type {string}
     * @memberof LearningPath
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LearningPath
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof LearningPath
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof LearningPath
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof LearningPath
     */
    status: LearningPathStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LearningPath
     */
    difficulty?: LearningPathDifficultyEnum;
    /**
     * Total estimated duration in minutes
     * @type {number}
     * @memberof LearningPath
     */
    estimatedDuration: number;
    /**
     * 
     * @type {string}
     * @memberof LearningPath
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof LearningPath
     */
    courseCount: number;
    /**
     * 
     * @type {number}
     * @memberof LearningPath
     */
    enrollmentCount?: number;
    /**
     * 
     * @type {number}
     * @memberof LearningPath
     */
    averageRating?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningPath
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof LearningPath
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof LearningPath
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const LearningPathStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Archived: 'archived'
} as const;
export type LearningPathStatusEnum = typeof LearningPathStatusEnum[keyof typeof LearningPathStatusEnum];

/**
 * @export
 */
export const LearningPathDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type LearningPathDifficultyEnum = typeof LearningPathDifficultyEnum[keyof typeof LearningPathDifficultyEnum];


/**
 * Check if a given object implements the LearningPath interface.
 */
export function instanceOfLearningPath(value: object): value is LearningPath {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('estimatedDuration' in value) || value['estimatedDuration'] === undefined) return false;
    if (!('courseCount' in value) || value['courseCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function LearningPathFromJSON(json: any): LearningPath {
    return LearningPathFromJSONTyped(json, false);
}

export function LearningPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningPath {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'category': json['category'],
        'status': json['status'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'estimatedDuration': json['estimatedDuration'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'courseCount': json['courseCount'],
        'enrollmentCount': json['enrollmentCount'] == null ? undefined : json['enrollmentCount'],
        'averageRating': json['averageRating'] == null ? undefined : json['averageRating'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function LearningPathToJSON(json: any): LearningPath {
    return LearningPathToJSONTyped(json, false);
}

export function LearningPathToJSONTyped(value?: LearningPath | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'category': value['category'],
        'status': value['status'],
        'difficulty': value['difficulty'],
        'estimatedDuration': value['estimatedDuration'],
        'thumbnailUrl': value['thumbnailUrl'],
        'courseCount': value['courseCount'],
        'enrollmentCount': value['enrollmentCount'],
        'averageRating': value['averageRating'],
        'tags': value['tags'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

