/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LearningPathDetailedAllOfUnlockConditions
 */
export interface LearningPathDetailedAllOfUnlockConditions {
    /**
     * 
     * @type {Array<string>}
     * @memberof LearningPathDetailedAllOfUnlockConditions
     */
    prerequisiteCourses?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof LearningPathDetailedAllOfUnlockConditions
     */
    minimumScore?: number;
}

/**
 * Check if a given object implements the LearningPathDetailedAllOfUnlockConditions interface.
 */
export function instanceOfLearningPathDetailedAllOfUnlockConditions(value: object): value is LearningPathDetailedAllOfUnlockConditions {
    return true;
}

export function LearningPathDetailedAllOfUnlockConditionsFromJSON(json: any): LearningPathDetailedAllOfUnlockConditions {
    return LearningPathDetailedAllOfUnlockConditionsFromJSONTyped(json, false);
}

export function LearningPathDetailedAllOfUnlockConditionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LearningPathDetailedAllOfUnlockConditions {
    if (json == null) {
        return json;
    }
    return {
        
        'prerequisiteCourses': json['prerequisiteCourses'] == null ? undefined : json['prerequisiteCourses'],
        'minimumScore': json['minimumScore'] == null ? undefined : json['minimumScore'],
    };
}

export function LearningPathDetailedAllOfUnlockConditionsToJSON(json: any): LearningPathDetailedAllOfUnlockConditions {
    return LearningPathDetailedAllOfUnlockConditionsToJSONTyped(json, false);
}

export function LearningPathDetailedAllOfUnlockConditionsToJSONTyped(value?: LearningPathDetailedAllOfUnlockConditions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prerequisiteCourses': value['prerequisiteCourses'],
        'minimumScore': value['minimumScore'],
    };
}

