/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Course } from './Course';
import {
    CourseFromJSON,
    CourseFromJSONTyped,
    CourseToJSON,
    CourseToJSONTyped,
} from './Course';

/**
 * 
 * @export
 * @interface ListCourses200Response
 */
export interface ListCourses200Response {
    /**
     * 
     * @type {Array<Course>}
     * @memberof ListCourses200Response
     */
    data: Array<Course>;
    /**
     * 
     * @type {number}
     * @memberof ListCourses200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ListCourses200Response
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListCourses200Response
     */
    offset: number;
}

/**
 * Check if a given object implements the ListCourses200Response interface.
 */
export function instanceOfListCourses200Response(value: object): value is ListCourses200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListCourses200ResponseFromJSON(json: any): ListCourses200Response {
    return ListCourses200ResponseFromJSONTyped(json, false);
}

export function ListCourses200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCourses200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CourseFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ListCourses200ResponseToJSON(json: any): ListCourses200Response {
    return ListCourses200ResponseToJSONTyped(json, false);
}

export function ListCourses200ResponseToJSONTyped(value?: ListCourses200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CourseToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

