/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LearningPath } from './LearningPath';
import {
    LearningPathFromJSON,
    LearningPathFromJSONTyped,
    LearningPathToJSON,
    LearningPathToJSONTyped,
} from './LearningPath';

/**
 * 
 * @export
 * @interface ListLearningPaths200Response
 */
export interface ListLearningPaths200Response {
    /**
     * 
     * @type {Array<LearningPath>}
     * @memberof ListLearningPaths200Response
     */
    data: Array<LearningPath>;
    /**
     * 
     * @type {number}
     * @memberof ListLearningPaths200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ListLearningPaths200Response
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListLearningPaths200Response
     */
    offset: number;
}

/**
 * Check if a given object implements the ListLearningPaths200Response interface.
 */
export function instanceOfListLearningPaths200Response(value: object): value is ListLearningPaths200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListLearningPaths200ResponseFromJSON(json: any): ListLearningPaths200Response {
    return ListLearningPaths200ResponseFromJSONTyped(json, false);
}

export function ListLearningPaths200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLearningPaths200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LearningPathFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ListLearningPaths200ResponseToJSON(json: any): ListLearningPaths200Response {
    return ListLearningPaths200ResponseToJSONTyped(json, false);
}

export function ListLearningPaths200ResponseToJSONTyped(value?: ListLearningPaths200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(LearningPathToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

