/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Assessment } from './Assessment';
import {
    AssessmentFromJSON,
    AssessmentFromJSONTyped,
    AssessmentToJSON,
    AssessmentToJSONTyped,
} from './Assessment';

/**
 * 
 * @export
 * @interface ListAssessments200Response
 */
export interface ListAssessments200Response {
    /**
     * 
     * @type {Array<Assessment>}
     * @memberof ListAssessments200Response
     */
    data: Array<Assessment>;
    /**
     * 
     * @type {number}
     * @memberof ListAssessments200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ListAssessments200Response
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListAssessments200Response
     */
    offset: number;
}

/**
 * Check if a given object implements the ListAssessments200Response interface.
 */
export function instanceOfListAssessments200Response(value: object): value is ListAssessments200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListAssessments200ResponseFromJSON(json: any): ListAssessments200Response {
    return ListAssessments200ResponseFromJSONTyped(json, false);
}

export function ListAssessments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAssessments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AssessmentFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ListAssessments200ResponseToJSON(json: any): ListAssessments200Response {
    return ListAssessments200ResponseToJSONTyped(json, false);
}

export function ListAssessments200ResponseToJSONTyped(value?: ListAssessments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(AssessmentToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

