/* tslint:disable */
/* eslint-disable */
/**
 * Learning Orchestrator API
 * Course orchestration and learning path management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCourseRequest
 */
export interface UpdateCourseRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    category?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateCourseRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    difficulty?: UpdateCourseRequestDifficultyEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    status?: UpdateCourseRequestStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseRequest
     */
    estimatedDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseRequest
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateCourseRequest
     */
    learningObjectives?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCourseRequest
     */
    isPublic?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateCourseRequest
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const UpdateCourseRequestDifficultyEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type UpdateCourseRequestDifficultyEnum = typeof UpdateCourseRequestDifficultyEnum[keyof typeof UpdateCourseRequestDifficultyEnum];

/**
 * @export
 */
export const UpdateCourseRequestStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Archived: 'archived'
} as const;
export type UpdateCourseRequestStatusEnum = typeof UpdateCourseRequestStatusEnum[keyof typeof UpdateCourseRequestStatusEnum];


/**
 * Check if a given object implements the UpdateCourseRequest interface.
 */
export function instanceOfUpdateCourseRequest(value: object): value is UpdateCourseRequest {
    return true;
}

export function UpdateCourseRequestFromJSON(json: any): UpdateCourseRequest {
    return UpdateCourseRequestFromJSONTyped(json, false);
}

export function UpdateCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'shortDescription': json['shortDescription'] == null ? undefined : json['shortDescription'],
        'category': json['category'] == null ? undefined : json['category'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'status': json['status'] == null ? undefined : json['status'],
        'estimatedDuration': json['estimatedDuration'] == null ? undefined : json['estimatedDuration'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'learningObjectives': json['learningObjectives'] == null ? undefined : json['learningObjectives'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateCourseRequestToJSON(json: any): UpdateCourseRequest {
    return UpdateCourseRequestToJSONTyped(json, false);
}

export function UpdateCourseRequestToJSONTyped(value?: UpdateCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'shortDescription': value['shortDescription'],
        'category': value['category'],
        'tags': value['tags'],
        'difficulty': value['difficulty'],
        'status': value['status'],
        'estimatedDuration': value['estimatedDuration'],
        'thumbnailUrl': value['thumbnailUrl'],
        'learningObjectives': value['learningObjectives'],
        'isPublic': value['isPublic'],
        'metadata': value['metadata'],
    };
}

