"""
Learner Management API

Learner profile and learning data management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.learner import Learner


class TestLearner(unittest.TestCase):
    """Learner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Learner:
        """Test Learner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Learner`
        """
        model = Learner()
        if include_optional:
            return Learner(
                id = '123e4567-e89b-12d3-a456-426614174000',
                tenant_id = '456e7890-e89b-12d3-a456-426614174000',
                email = 'learner@example.com',
                first_name = 'Jane',
                last_name = 'Smith',
                status = 'active',
                avatar = 'https://example.com/avatar.jpg',
                timezone = 'America/New_York',
                language = 'en',
                department = 'Engineering',
                job_title = 'Software Engineer',
                manager = '234e5678-e89b-12d3-a456-426614174000',
                last_login_at = '2023-12-01T10:30:00Z',
                enrollment_count = 5,
                completion_count = 3,
                total_learning_minutes = 1250,
                metadata = {employeeId=EMP001, hireDate=2022-01-15},
                created_at = '2023-01-01T00:00:00Z',
                updated_at = '2023-12-01T10:30:00Z'
            )
        else:
            return Learner(
                id = '123e4567-e89b-12d3-a456-426614174000',
                tenant_id = '456e7890-e89b-12d3-a456-426614174000',
                email = 'learner@example.com',
                first_name = 'Jane',
                last_name = 'Smith',
                status = 'active',
                created_at = '2023-01-01T00:00:00Z',
                updated_at = '2023-12-01T10:30:00Z',
        )
        """

    def testLearner(self):
        """Test Learner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
