"""
Learner Management API

Learner profile and learning data management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.learner_analytics import LearnerAnalytics


class TestLearnerAnalytics(unittest.TestCase):
    """LearnerAnalytics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearnerAnalytics:
        """Test LearnerAnalytics
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LearnerAnalytics`
        """
        model = LearnerAnalytics()
        if include_optional:
            return LearnerAnalytics(
                learner_id = '123e4567-e89b-12d3-a456-426614174000',
                range = '30d',
                total_learning_time = 1250,
                completion_rate = 75.5,
                streak_days = 7,
                courses_started = 5,
                courses_completed = 3,
                average_session_length = 45,
                activity_data = [
                    aivo_sdk.models.learner_analytics_activity_data_inner.LearnerAnalytics_activityData_inner(
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        minutes_learned = 56, 
                        sessions_count = 56, )
                    ],
                subject_breakdown = [
                    aivo_sdk.models.learner_analytics_subject_breakdown_inner.LearnerAnalytics_subjectBreakdown_inner(
                        subject = '', 
                        minutes_learned = 56, 
                        percentage = 1.337, )
                    ]
            )
        else:
            return LearnerAnalytics(
                learner_id = '123e4567-e89b-12d3-a456-426614174000',
                range = '30d',
                total_learning_time = 1250,
                completion_rate = 75.5,
                streak_days = 7,
                activity_data = [
                    aivo_sdk.models.learner_analytics_activity_data_inner.LearnerAnalytics_activityData_inner(
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        minutes_learned = 56, 
                        sessions_count = 56, )
                    ],
        )
        """

    def testLearnerAnalytics(self):
        """Test LearnerAnalytics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
