# coding: utf-8

"""
    Learner Management API

    Learner profile and learning data management service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.learner_profile_preferences import LearnerProfilePreferences

class TestLearnerProfilePreferences(unittest.TestCase):
    """LearnerProfilePreferences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearnerProfilePreferences:
        """Test LearnerProfilePreferences
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LearnerProfilePreferences`
        """
        model = LearnerProfilePreferences()
        if include_optional:
            return LearnerProfilePreferences(
                learning_style = 'visual',
                difficulty_level = 'intermediate',
                notifications_enabled = True,
                email_digest = True,
                preferred_learning_time = 'morning'
            )
        else:
            return LearnerProfilePreferences(
        )
        """

    def testLearnerProfilePreferences(self):
        """Test LearnerProfilePreferences"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
