# coding: utf-8

"""
    Learner Management API

    Learner profile and learning data management service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.learner_profile_goals_inner import LearnerProfileGoalsInner

class TestLearnerProfileGoalsInner(unittest.TestCase):
    """LearnerProfileGoalsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearnerProfileGoalsInner:
        """Test LearnerProfileGoalsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LearnerProfileGoalsInner`
        """
        model = LearnerProfileGoalsInner()
        if include_optional:
            return LearnerProfileGoalsInner(
                goal_id = '',
                title = '',
                description = '',
                target_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = 'active',
                progress = 0
            )
        else:
            return LearnerProfileGoalsInner(
        )
        """

    def testLearnerProfileGoalsInner(self):
        """Test LearnerProfileGoalsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
