# coding: utf-8

"""
    Learner Management API

    Learner profile and learning data management service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.award_achievement_request import AwardAchievementRequest

class TestAwardAchievementRequest(unittest.TestCase):
    """AwardAchievementRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwardAchievementRequest:
        """Test AwardAchievementRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AwardAchievementRequest`
        """
        model = AwardAchievementRequest()
        if include_optional:
            return AwardAchievementRequest(
                type = 'course_completion',
                title = 'JavaScript Master',
                description = 'Completed advanced JavaScript course with 95% score',
                icon_url = 'https://example.com/icons/js-master.png',
                badge_url = 'https://example.com/badges/js-master.png',
                points = 100,
                metadata = { }
            )
        else:
            return AwardAchievementRequest(
                type = 'course_completion',
                title = 'JavaScript Master',
                description = 'Completed advanced JavaScript course with 95% score',
        )
        """

    def testAwardAchievementRequest(self):
        """Test AwardAchievementRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
