/* tslint:disable */
/* eslint-disable */
/**
 * Enrollment Management API
 * Learner enrollment and course assignment service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrollmentProgressAssessmentScoresInner } from './EnrollmentProgressAssessmentScoresInner';
import {
    EnrollmentProgressAssessmentScoresInnerFromJSON,
    EnrollmentProgressAssessmentScoresInnerFromJSONTyped,
    EnrollmentProgressAssessmentScoresInnerToJSON,
    EnrollmentProgressAssessmentScoresInnerToJSONTyped,
} from './EnrollmentProgressAssessmentScoresInner';

/**
 * 
 * @export
 * @interface EnrollmentProgress
 */
export interface EnrollmentProgress {
    /**
     * 
     * @type {string}
     * @memberof EnrollmentProgress
     */
    enrollmentId: string;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentProgress
     */
    progressPercentage: number;
    /**
     * 
     * @type {number}
     * @memberof EnrollmentProgress
     */
    timeSpentMinutes: number;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentProgress
     */
    lastAccessedAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnrollmentProgress
     */
    completedModules?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EnrollmentProgress
     */
    currentModule?: string;
    /**
     * 
     * @type {Array<EnrollmentProgressAssessmentScoresInner>}
     * @memberof EnrollmentProgress
     */
    assessmentScores?: Array<EnrollmentProgressAssessmentScoresInner>;
}

/**
 * Check if a given object implements the EnrollmentProgress interface.
 */
export function instanceOfEnrollmentProgress(value: object): value is EnrollmentProgress {
    if (!('enrollmentId' in value) || value['enrollmentId'] === undefined) return false;
    if (!('progressPercentage' in value) || value['progressPercentage'] === undefined) return false;
    if (!('timeSpentMinutes' in value) || value['timeSpentMinutes'] === undefined) return false;
    if (!('lastAccessedAt' in value) || value['lastAccessedAt'] === undefined) return false;
    return true;
}

export function EnrollmentProgressFromJSON(json: any): EnrollmentProgress {
    return EnrollmentProgressFromJSONTyped(json, false);
}

export function EnrollmentProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollmentProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'enrollmentId': json['enrollmentId'],
        'progressPercentage': json['progressPercentage'],
        'timeSpentMinutes': json['timeSpentMinutes'],
        'lastAccessedAt': (new Date(json['lastAccessedAt'])),
        'completedModules': json['completedModules'] == null ? undefined : json['completedModules'],
        'currentModule': json['currentModule'] == null ? undefined : json['currentModule'],
        'assessmentScores': json['assessmentScores'] == null ? undefined : ((json['assessmentScores'] as Array<any>).map(EnrollmentProgressAssessmentScoresInnerFromJSON)),
    };
}

export function EnrollmentProgressToJSON(json: any): EnrollmentProgress {
    return EnrollmentProgressToJSONTyped(json, false);
}

export function EnrollmentProgressToJSONTyped(value?: EnrollmentProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enrollmentId': value['enrollmentId'],
        'progressPercentage': value['progressPercentage'],
        'timeSpentMinutes': value['timeSpentMinutes'],
        'lastAccessedAt': ((value['lastAccessedAt']).toISOString()),
        'completedModules': value['completedModules'],
        'currentModule': value['currentModule'],
        'assessmentScores': value['assessmentScores'] == null ? undefined : ((value['assessmentScores'] as Array<any>).map(EnrollmentProgressAssessmentScoresInnerToJSON)),
    };
}

