/* tslint:disable */
/* eslint-disable */
/**
 * Enrollment Management API
 * Learner enrollment and course assignment service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Enrollment } from './Enrollment';
import {
    EnrollmentFromJSON,
    EnrollmentFromJSONTyped,
    EnrollmentToJSON,
    EnrollmentToJSONTyped,
} from './Enrollment';

/**
 * 
 * @export
 * @interface ListEnrollments200Response
 */
export interface ListEnrollments200Response {
    /**
     * 
     * @type {Array<Enrollment>}
     * @memberof ListEnrollments200Response
     */
    data: Array<Enrollment>;
    /**
     * 
     * @type {number}
     * @memberof ListEnrollments200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ListEnrollments200Response
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ListEnrollments200Response
     */
    offset: number;
}

/**
 * Check if a given object implements the ListEnrollments200Response interface.
 */
export function instanceOfListEnrollments200Response(value: object): value is ListEnrollments200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function ListEnrollments200ResponseFromJSON(json: any): ListEnrollments200Response {
    return ListEnrollments200ResponseFromJSONTyped(json, false);
}

export function ListEnrollments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEnrollments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(EnrollmentFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function ListEnrollments200ResponseToJSON(json: any): ListEnrollments200Response {
    return ListEnrollments200ResponseToJSONTyped(json, false);
}

export function ListEnrollments200ResponseToJSONTyped(value?: ListEnrollments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(EnrollmentToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

