# coding: utf-8

# flake8: noqa

"""
Learner Management API

Learner profile and learning data management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AchievementsApi",
    "AnalyticsApi",
    "BulkOperationsApi",
    "LearnerProfileApi",
    "LearnersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Achievement",
    "AwardAchievementRequest",
    "BulkImportRequest",
    "BulkImportResponse",
    "BulkImportResponseErrorsInner",
    "CreateLearnerRequest",
    "Error",
    "Learner",
    "LearnerAnalytics",
    "LearnerAnalyticsActivityDataInner",
    "LearnerAnalyticsSubjectBreakdownInner",
    "LearnerProfile",
    "LearnerProfileGoalsInner",
    "LearnerProfilePreferences",
    "LearnerProfileSkillsInner",
    "ListLearners200Response",
    "UpdateLearnerProfileRequest",
    "UpdateLearnerProfileRequestPreferences",
    "UpdateLearnerRequest",
    "ValidationError",
    "ValidationErrorValidationErrorsInner",
]

# import apis into sdk package
from aivo_sdk.api.achievements_api import AchievementsApi as AchievementsApi
from aivo_sdk.api.analytics_api import AnalyticsApi as AnalyticsApi
from aivo_sdk.api.bulk_operations_api import BulkOperationsApi as BulkOperationsApi
from aivo_sdk.api.learner_profile_api import LearnerProfileApi as LearnerProfileApi
from aivo_sdk.api.learners_api import LearnersApi as LearnersApi

# import ApiClient
from aivo_sdk.api_response import ApiResponse as ApiResponse
from aivo_sdk.api_client import ApiClient as ApiClient
from aivo_sdk.configuration import Configuration as Configuration
from aivo_sdk.exceptions import OpenApiException as OpenApiException
from aivo_sdk.exceptions import ApiTypeError as ApiTypeError
from aivo_sdk.exceptions import ApiValueError as ApiValueError
from aivo_sdk.exceptions import ApiKeyError as ApiKeyError
from aivo_sdk.exceptions import ApiAttributeError as ApiAttributeError
from aivo_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from aivo_sdk.models.achievement import Achievement as Achievement
from aivo_sdk.models.award_achievement_request import (
    AwardAchievementRequest as AwardAchievementRequest,
)
from aivo_sdk.models.bulk_import_request import BulkImportRequest as BulkImportRequest
from aivo_sdk.models.bulk_import_response import BulkImportResponse as BulkImportResponse
from aivo_sdk.models.bulk_import_response_errors_inner import (
    BulkImportResponseErrorsInner as BulkImportResponseErrorsInner,
)
from aivo_sdk.models.create_learner_request import CreateLearnerRequest as CreateLearnerRequest
from aivo_sdk.models.error import Error as Error
from aivo_sdk.models.learner import Learner as Learner
from aivo_sdk.models.learner_analytics import LearnerAnalytics as LearnerAnalytics
from aivo_sdk.models.learner_analytics_activity_data_inner import (
    LearnerAnalyticsActivityDataInner as LearnerAnalyticsActivityDataInner,
)
from aivo_sdk.models.learner_analytics_subject_breakdown_inner import (
    LearnerAnalyticsSubjectBreakdownInner as LearnerAnalyticsSubjectBreakdownInner,
)
from aivo_sdk.models.learner_profile import LearnerProfile as LearnerProfile
from aivo_sdk.models.learner_profile_goals_inner import (
    LearnerProfileGoalsInner as LearnerProfileGoalsInner,
)
from aivo_sdk.models.learner_profile_preferences import (
    LearnerProfilePreferences as LearnerProfilePreferences,
)
from aivo_sdk.models.learner_profile_skills_inner import (
    LearnerProfileSkillsInner as LearnerProfileSkillsInner,
)
from aivo_sdk.models.list_learners200_response import (
    ListLearners200Response as ListLearners200Response,
)
from aivo_sdk.models.update_learner_profile_request import (
    UpdateLearnerProfileRequest as UpdateLearnerProfileRequest,
)
from aivo_sdk.models.update_learner_profile_request_preferences import (
    UpdateLearnerProfileRequestPreferences as UpdateLearnerProfileRequestPreferences,
)
from aivo_sdk.models.update_learner_request import UpdateLearnerRequest as UpdateLearnerRequest
from aivo_sdk.models.validation_error import ValidationError as ValidationError
from aivo_sdk.models.validation_error_validation_errors_inner import (
    ValidationErrorValidationErrorsInner as ValidationErrorValidationErrorsInner,
)
