"""
Learning Orchestrator API

Course orchestration and learning path management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.submit_assessment_request import SubmitAssessmentRequest


class TestSubmitAssessmentRequest(unittest.TestCase):
    """SubmitAssessmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitAssessmentRequest:
        """Test SubmitAssessmentRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SubmitAssessmentRequest`
        """
        model = SubmitAssessmentRequest()
        if include_optional:
            return SubmitAssessmentRequest(
                answers = [
                    aivo_sdk.models.submit_assessment_request_answers_inner.SubmitAssessmentRequest_answers_inner(
                        question_id = '', 
                        answer = null, )
                    ],
                time_spent = 45
            )
        else:
            return SubmitAssessmentRequest(
                answers = [
                    aivo_sdk.models.submit_assessment_request_answers_inner.SubmitAssessmentRequest_answers_inner(
                        question_id = '', 
                        answer = null, )
                    ],
        )
        """

    def testSubmitAssessmentRequest(self):
        """Test SubmitAssessmentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
