# coding: utf-8

"""
    Learning Orchestrator API

    Course orchestration and learning path management service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.create_course_request import CreateCourseRequest

class TestCreateCourseRequest(unittest.TestCase):
    """CreateCourseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCourseRequest:
        """Test CreateCourseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCourseRequest`
        """
        model = CreateCourseRequest()
        if include_optional:
            return CreateCourseRequest(
                title = 'Advanced JavaScript Programming',
                description = 'Master advanced JavaScript concepts and modern frameworks',
                short_description = 'Learn advanced JS concepts',
                category = 'Programming',
                tags = [
                    ''
                    ],
                difficulty = 'advanced',
                estimated_duration = 1200,
                thumbnail_url = 'https://example.com/thumbnails/js-course.jpg',
                instructor_id = 'inst_456e7890-e89b-12d3-a456-426614174000',
                prerequisites = [
                    ''
                    ],
                learning_objectives = [
                    ''
                    ],
                is_public = True,
                metadata = { }
            )
        else:
            return CreateCourseRequest(
                title = 'Advanced JavaScript Programming',
                description = 'Master advanced JavaScript concepts and modern frameworks',
                category = 'Programming',
                difficulty = 'advanced',
        )
        """

    def testCreateCourseRequest(self):
        """Test CreateCourseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
