"""
Learning Orchestrator API

Course orchestration and learning path management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.submit_assessment_request_answers_inner import (
    SubmitAssessmentRequestAnswersInner,
)


class TestSubmitAssessmentRequestAnswersInner(unittest.TestCase):
    """SubmitAssessmentRequestAnswersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitAssessmentRequestAnswersInner:
        """Test SubmitAssessmentRequestAnswersInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SubmitAssessmentRequestAnswersInner`
        """
        model = SubmitAssessmentRequestAnswersInner()
        if include_optional:
            return SubmitAssessmentRequestAnswersInner(
                question_id = '',
                answer = None
            )
        else:
            return SubmitAssessmentRequestAnswersInner(
                question_id = '',
                answer = None,
        )
        """

    def testSubmitAssessmentRequestAnswersInner(self):
        """Test SubmitAssessmentRequestAnswersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
