# coding: utf-8

"""
    Learning Orchestrator API

    Course orchestration and learning path management service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aivo_sdk.models.update_course_request import UpdateCourseRequest

class TestUpdateCourseRequest(unittest.TestCase):
    """UpdateCourseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCourseRequest:
        """Test UpdateCourseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCourseRequest`
        """
        model = UpdateCourseRequest()
        if include_optional:
            return UpdateCourseRequest(
                title = '012',
                description = '0123456789',
                short_description = '',
                category = '',
                tags = [
                    ''
                    ],
                difficulty = 'beginner',
                status = 'draft',
                estimated_duration = 1,
                thumbnail_url = '',
                learning_objectives = [
                    ''
                    ],
                is_public = True,
                metadata = { }
            )
        else:
            return UpdateCourseRequest(
        )
        """

    def testUpdateCourseRequest(self):
        """Test UpdateCourseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
