"""
Learning Orchestrator API

Course orchestration and learning path management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.learning_path_detailed import LearningPathDetailed


class TestLearningPathDetailed(unittest.TestCase):
    """LearningPathDetailed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearningPathDetailed:
        """Test LearningPathDetailed
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LearningPathDetailed`
        """
        model = LearningPathDetailed()
        if include_optional:
            return LearningPathDetailed(
                id = 'path_123e4567-e89b-12d3-a456-426614174000',
                title = 'Full Stack Developer Path',
                description = 'Comprehensive path to become a full stack developer',
                category = 'Software Development',
                status = 'published',
                difficulty = 'intermediate',
                estimated_duration = 7200,
                thumbnail_url = 'https://example.com/thumbnails/fullstack-path.jpg',
                course_count = 6,
                enrollment_count = 500,
                average_rating = 4.5,
                tags = [javascript, react, nodejs, database],
                created_at = '2023-01-01T00:00:00Z',
                updated_at = '2023-12-01T10:30:00Z',
                courses = [
                    aivo_sdk.models.learning_path_detailed_all_of_courses.LearningPathDetailed_allOf_courses(
                        course_id = '', 
                        course = aivo_sdk.models.course.Course(
                            id = 'course_123e4567-e89b-12d3-a456-426614174000', 
                            title = 'Advanced JavaScript Programming', 
                            description = 'Master advanced JavaScript concepts and modern frameworks', 
                            short_description = 'Learn advanced JS concepts', 
                            category = 'Programming', 
                            tags = [javascript, programming, web-development], 
                            difficulty = 'advanced', 
                            status = 'published', 
                            estimated_duration = 1200, 
                            thumbnail_url = 'https://example.com/thumbnails/js-course.jpg', 
                            instructor_id = 'inst_456e7890-e89b-12d3-a456-426614174000', 
                            prerequisites = [course_abc123, course_def456], 
                            learning_objectives = [Understand closures, Master async/await, Build modern web apps], 
                            module_count = 8, 
                            enrollment_count = 1250, 
                            average_rating = 4.7, 
                            review_count = 127, 
                            is_public = True, 
                            metadata = { }, 
                            created_at = '2023-01-01T00:00:00Z', 
                            updated_at = '2023-12-01T10:30:00Z', ), 
                        order = 56, 
                        is_optional = True, 
                        unlock_conditions = aivo_sdk.models.learning_path_detailed_all_of_unlock_conditions.LearningPathDetailed_allOf_unlockConditions(
                            prerequisite_courses = [
                                ''
                                ], 
                            minimum_score = 0, ), )
                    ]
            )
        else:
            return LearningPathDetailed(
                id = 'path_123e4567-e89b-12d3-a456-426614174000',
                title = 'Full Stack Developer Path',
                description = 'Comprehensive path to become a full stack developer',
                category = 'Software Development',
                status = 'published',
                estimated_duration = 7200,
                course_count = 6,
                created_at = '2023-01-01T00:00:00Z',
                updated_at = '2023-12-01T10:30:00Z',
        )
        """

    def testLearningPathDetailed(self):
        """Test LearningPathDetailed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
