"""
Learning Orchestrator API

Course orchestration and learning path management service

The version of the OpenAPI document: 1.0.0
Contact: api-support@aivo.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aivo_sdk.models.course_detailed_all_of_requirements import CourseDetailedAllOfRequirements


class TestCourseDetailedAllOfRequirements(unittest.TestCase):
    """CourseDetailedAllOfRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourseDetailedAllOfRequirements:
        """Test CourseDetailedAllOfRequirements
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CourseDetailedAllOfRequirements`
        """
        model = CourseDetailedAllOfRequirements()
        if include_optional:
            return CourseDetailedAllOfRequirements(
                system_requirements = [
                    ''
                    ],
                software_requirements = [
                    ''
                    ]
            )
        else:
            return CourseDetailedAllOfRequirements(
        )
        """

    def testCourseDetailedAllOfRequirements(self):
        """Test CourseDetailedAllOfRequirements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
