/* tslint:disable */
/* eslint-disable */
/**
 * Tenant Management API
 * Multi-tenant organization management service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantSettingsBranding
 */
export interface TenantSettingsBranding {
    /**
     * 
     * @type {string}
     * @memberof TenantSettingsBranding
     */
    primaryColor?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettingsBranding
     */
    secondaryColor?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettingsBranding
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof TenantSettingsBranding
     */
    favicon?: string;
}

/**
 * Check if a given object implements the TenantSettingsBranding interface.
 */
export function instanceOfTenantSettingsBranding(value: object): value is TenantSettingsBranding {
    return true;
}

export function TenantSettingsBrandingFromJSON(json: any): TenantSettingsBranding {
    return TenantSettingsBrandingFromJSONTyped(json, false);
}

export function TenantSettingsBrandingFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantSettingsBranding {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryColor': json['primaryColor'] == null ? undefined : json['primaryColor'],
        'secondaryColor': json['secondaryColor'] == null ? undefined : json['secondaryColor'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'favicon': json['favicon'] == null ? undefined : json['favicon'],
    };
}

export function TenantSettingsBrandingToJSON(json: any): TenantSettingsBranding {
    return TenantSettingsBrandingToJSONTyped(json, false);
}

export function TenantSettingsBrandingToJSONTyped(value?: TenantSettingsBranding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primaryColor': value['primaryColor'],
        'secondaryColor': value['secondaryColor'],
        'logo': value['logo'],
        'favicon': value['favicon'],
    };
}

