[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
]
ignore = [
    "ANN001",  # Missing type annotation for function argument
    "ANN101",  # Missing type annotation for self in method
    "ANN204",  # Missing return type annotation for special method
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
