/* tslint:disable */
/* eslint-disable */
/**
 * Admin Portal Aggregator API
 * Read-only aggregator API for admin dashboard widgets and KPIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionDetailsRenewal
 */
export interface SubscriptionDetailsRenewal {
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionDetailsRenewal
     */
    nextBillingDate: Date;
    /**
     * Next billing amount
     * @type {number}
     * @memberof SubscriptionDetailsRenewal
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDetailsRenewal
     */
    currency?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionDetailsRenewal
     */
    autoRenew: boolean;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionDetailsRenewal
     */
    daysUntilRenewal?: number;
}

/**
 * Check if a given object implements the SubscriptionDetailsRenewal interface.
 */
export function instanceOfSubscriptionDetailsRenewal(value: object): value is SubscriptionDetailsRenewal {
    if (!('nextBillingDate' in value) || value['nextBillingDate'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('autoRenew' in value) || value['autoRenew'] === undefined) return false;
    return true;
}

export function SubscriptionDetailsRenewalFromJSON(json: any): SubscriptionDetailsRenewal {
    return SubscriptionDetailsRenewalFromJSONTyped(json, false);
}

export function SubscriptionDetailsRenewalFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionDetailsRenewal {
    if (json == null) {
        return json;
    }
    return {
        
        'nextBillingDate': (new Date(json['nextBillingDate'])),
        'amount': json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'autoRenew': json['autoRenew'],
        'daysUntilRenewal': json['daysUntilRenewal'] == null ? undefined : json['daysUntilRenewal'],
    };
}

export function SubscriptionDetailsRenewalToJSON(json: any): SubscriptionDetailsRenewal {
    return SubscriptionDetailsRenewalToJSONTyped(json, false);
}

export function SubscriptionDetailsRenewalToJSONTyped(value?: SubscriptionDetailsRenewal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextBillingDate': ((value['nextBillingDate']).toISOString().substring(0,10)),
        'amount': value['amount'],
        'currency': value['currency'],
        'autoRenew': value['autoRenew'],
        'daysUntilRenewal': value['daysUntilRenewal'],
    };
}

