/* tslint:disable */
/* eslint-disable */
/**
 * Admin Portal Aggregator API
 * Read-only aggregator API for admin dashboard widgets and KPIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamOverviewPendingInvitesByRole
 */
export interface TeamOverviewPendingInvitesByRole {
    /**
     * 
     * @type {number}
     * @memberof TeamOverviewPendingInvitesByRole
     */
    tenantAdmin?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamOverviewPendingInvitesByRole
     */
    instructor?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamOverviewPendingInvitesByRole
     */
    learner?: number;
}

/**
 * Check if a given object implements the TeamOverviewPendingInvitesByRole interface.
 */
export function instanceOfTeamOverviewPendingInvitesByRole(value: object): value is TeamOverviewPendingInvitesByRole {
    return true;
}

export function TeamOverviewPendingInvitesByRoleFromJSON(json: any): TeamOverviewPendingInvitesByRole {
    return TeamOverviewPendingInvitesByRoleFromJSONTyped(json, false);
}

export function TeamOverviewPendingInvitesByRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamOverviewPendingInvitesByRole {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantAdmin': json['tenant_admin'] == null ? undefined : json['tenant_admin'],
        'instructor': json['instructor'] == null ? undefined : json['instructor'],
        'learner': json['learner'] == null ? undefined : json['learner'],
    };
}

export function TeamOverviewPendingInvitesByRoleToJSON(json: any): TeamOverviewPendingInvitesByRole {
    return TeamOverviewPendingInvitesByRoleToJSONTyped(json, false);
}

export function TeamOverviewPendingInvitesByRoleToJSONTyped(value?: TeamOverviewPendingInvitesByRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant_admin': value['tenantAdmin'],
        'instructor': value['instructor'],
        'learner': value['learner'],
    };
}

