/* tslint:disable */
/* eslint-disable */
/**
 * Admin Portal Aggregator API
 * Read-only aggregator API for admin dashboard widgets and KPIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamOverviewRecentActivity
 */
export interface TeamOverviewRecentActivity {
    /**
     * 
     * @type {number}
     * @memberof TeamOverviewRecentActivity
     */
    newUsersThisWeek?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamOverviewRecentActivity
     */
    newUsersThisMonth?: number;
    /**
     * 
     * @type {Date}
     * @memberof TeamOverviewRecentActivity
     */
    lastUserJoined?: Date;
}

/**
 * Check if a given object implements the TeamOverviewRecentActivity interface.
 */
export function instanceOfTeamOverviewRecentActivity(value: object): value is TeamOverviewRecentActivity {
    return true;
}

export function TeamOverviewRecentActivityFromJSON(json: any): TeamOverviewRecentActivity {
    return TeamOverviewRecentActivityFromJSONTyped(json, false);
}

export function TeamOverviewRecentActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamOverviewRecentActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'newUsersThisWeek': json['newUsersThisWeek'] == null ? undefined : json['newUsersThisWeek'],
        'newUsersThisMonth': json['newUsersThisMonth'] == null ? undefined : json['newUsersThisMonth'],
        'lastUserJoined': json['lastUserJoined'] == null ? undefined : (new Date(json['lastUserJoined'])),
    };
}

export function TeamOverviewRecentActivityToJSON(json: any): TeamOverviewRecentActivity {
    return TeamOverviewRecentActivityToJSONTyped(json, false);
}

export function TeamOverviewRecentActivityToJSONTyped(value?: TeamOverviewRecentActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newUsersThisWeek': value['newUsersThisWeek'],
        'newUsersThisMonth': value['newUsersThisMonth'],
        'lastUserJoined': value['lastUserJoined'] == null ? undefined : ((value['lastUserJoined']).toISOString()),
    };
}

