/* tslint:disable */
/* eslint-disable */
/**
 * Admin Portal Aggregator API
 * Read-only aggregator API for admin dashboard widgets and KPIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TenantSummaryLearners
 */
export interface TenantSummaryLearners {
    /**
     * Total number of learners
     * @type {number}
     * @memberof TenantSummaryLearners
     */
    total: number;
    /**
     * Number of active learners
     * @type {number}
     * @memberof TenantSummaryLearners
     */
    active: number;
    /**
     * Number of inactive learners
     * @type {number}
     * @memberof TenantSummaryLearners
     */
    inactive: number;
    /**
     * Number of pending learners
     * @type {number}
     * @memberof TenantSummaryLearners
     */
    pending: number;
}

/**
 * Check if a given object implements the TenantSummaryLearners interface.
 */
export function instanceOfTenantSummaryLearners(value: object): value is TenantSummaryLearners {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('inactive' in value) || value['inactive'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function TenantSummaryLearnersFromJSON(json: any): TenantSummaryLearners {
    return TenantSummaryLearnersFromJSONTyped(json, false);
}

export function TenantSummaryLearnersFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantSummaryLearners {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'active': json['active'],
        'inactive': json['inactive'],
        'pending': json['pending'],
    };
}

export function TenantSummaryLearnersToJSON(json: any): TenantSummaryLearners {
    return TenantSummaryLearnersToJSONTyped(json, false);
}

export function TenantSummaryLearnersToJSONTyped(value?: TenantSummaryLearners | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'active': value['active'],
        'inactive': value['inactive'],
        'pending': value['pending'],
    };
}

