openapi: 3.0.3
info:
  title: Analytics Service API
  description: REST API for analytics data aggregation and reporting
  version: 1.0.0
  contact:
    name: Aivo Platform Team
    email: platform@aivo.com

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.aivo.com/analytics
    description: Production server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the analytics service
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, unhealthy]
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string

  /metrics/aggregated:
    get:
      summary: Get aggregated analytics metrics
      description: Retrieve aggregated metrics for reporting and dashboards
      operationId: getAggregatedMetrics
      parameters:
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Start date for metrics (YYYY-MM-DD)
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: End date for metrics (YYYY-MM-DD)
        - name: granularity
          in: query
          required: false
          schema:
            type: string
            enum: [minute, hour, day, week, month]
            default: day
          description: Granularity of the metrics
      responses:
        '200':
          description: Aggregated metrics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AggregatedMetric'
                  total_count:
                    type: integer
                  date_range:
                    type: object
                    properties:
                      start:
                        type: string
                        format: date
                      end:
                        type: string
                        format: date

components:
  schemas:
    AggregatedMetric:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        total_events:
          type: integer
        unique_learners:
          type: integer
        sessions_started:
          type: integer
        lessons_completed:
          type: integer
        assessments_completed:
          type: integer
        avg_session_duration:
          type: number
          format: float