openapi: 3.1.0
info:
  title: Subject-Brain Service API
  description: 'AI-powered planner and runtime for per-learner-subject GPU pods with
    autoscaling.


    This service provides:

    - Personalized activity planning based on learner baseline and mastery levels

    - Per-learner-subject runtime pods with GPU autoscaling

    - Kubernetes HPA based on GPU queue depth and resource utilization

    - TTL-based scale-to-zero for cost optimization


    ## Features


    ### Planner

    - Analyzes learner baseline and mastery levels

    - Considers coursework topics and teacher constraints

    - Generates optimal activity sequences for learning sessions

    - Supports multiple subjects and activity types


    ### Runtime Manager

    - Creates ephemeral pods per active learner-subject

    - GPU resource allocation and management

    - Horizontal Pod Autoscaling based on queue depth

    - Automatic cleanup of idle runtimes (TTL scale-to-zero)


    ### Monitoring

    - Real-time metrics for scaling decisions

    - Runtime status tracking

    - Performance analytics for optimization

    '
  version: 1.0.0
  contact:
    name: AI Learning Platform Team
    email: platform@aivo.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: http://localhost:8000
  description: Development server
- url: https://api.aivo.com/subject-brain
  description: Production server
paths:
  /health:
    get:
      summary: Health check
      description: Check service health status
      operationId: subjectBrainHealthCheck
      tags:
      - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  service:
                    type: string
                    example: subject-brain-svc
                  version:
                    type: string
                    example: 1.0.0
  /metrics:
    get:
      summary: Get service metrics
      description: Retrieve current service and scaling metrics
      operationId: getMetrics
      tags:
      - Monitoring
      responses:
        '200':
          description: Current metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  service_metrics:
                    type: object
                    properties:
                      active_runtimes:
                        type: integer
                        description: Number of active runtime pods
                      total_pods:
                        type: integer
                        description: Total pods managed
                  scaling_metrics:
                    type: object
                    properties:
                      total_gpu_queue_depth:
                        type: integer
                        description: Total GPU queue depth across all runtimes
                      average_cpu_utilization:
                        type: number
                        description: Average CPU utilization percentage
                      average_memory_usage_mb:
                        type: number
                        description: Average memory usage in MB
                      pending_requests:
                        type: integer
                        description: Number of pending runtime requests
        '500':
          description: Failed to get metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /plan:
    post:
      summary: Create activity plan
      description: 'Create a personalized activity plan for a learner in a specific
        subject.

        The planner analyzes learner baseline, mastery levels, coursework topics,

        and teacher constraints to generate an optimal learning sequence.

        '
      operationId: createActivityPlan
      tags:
      - Planner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlannerRequest'
            example:
              learner_id: learner_123
              subject: mathematics
              session_duration_minutes: 30
              force_refresh: false
      responses:
        '200':
          description: Activity plan created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlannerResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '501':
          description: Service integration required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /runtime/{runtime_id}:
    get:
      summary: Get runtime status
      description: Retrieve the current status and metrics of a specific runtime pod
      operationId: getRuntimeStatus
      tags:
      - Runtime
      parameters:
      - name: runtime_id
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for the runtime
        example: runtime_456
      responses:
        '200':
          description: Runtime status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuntimeStatusResponse'
        '404':
          description: Runtime not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to get runtime status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Terminate runtime
      description: Manually terminate a specific runtime pod
      operationId: terminateRuntime
      tags:
      - Runtime
      parameters:
      - name: runtime_id
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for the runtime
        example: runtime_456
      responses:
        '200':
          description: Runtime termination initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Runtime runtime_456 termination initiated
                  status:
                    type: string
                    example: terminating
        '404':
          description: Runtime not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to terminate runtime
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cleanup:
    post:
      summary: Cleanup idle runtimes
      description: Manually trigger cleanup of idle runtime pods based on TTL
      operationId: cleanupIdleRuntimes
      tags:
      - Runtime
      responses:
        '200':
          description: Cleanup completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Cleanup completed
                  cleaned_up_runtimes:
                    type: array
                    items:
                      type: string
                    example:
                    - runtime_123
                    - runtime_456
                  count:
                    type: integer
                    example: 2
        '500':
          description: Failed to cleanup runtimes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    PlannerRequest:
      type: object
      required:
      - learner_id
      - subject
      properties:
        learner_id:
          type: string
          description: Unique identifier for the learner
          example: 62991b68-f707-414a-acce-9b055e1b4f8b
        subject:
          type: string
          enum:
          - mathematics
          - science
          - language_arts
          - social_studies
          - foreign_language
          description: Subject area for the learning session
          example: mathematics
        session_duration_minutes:
          type: integer
          minimum: 5
          maximum: 120
          default: 30
          description: Duration of the learning session in minutes
          example: 30
        force_refresh:
          type: boolean
          default: false
          description: Force regeneration of plan (ignore cache)
          example: false
    PlannerResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the plan was created successfully
          example: true
        plan:
          $ref: '#/components/schemas/ActivityPlan'
        runtime_request:
          $ref: '#/components/schemas/RuntimeRequest'
        error_message:
          type: string
          nullable: true
          description: Error message if plan creation failed
          example: null
        processing_time_ms:
          type: integer
          description: Time taken to process the request in milliseconds
          example: 250
    ActivityPlan:
      type: object
      properties:
        plan_id:
          type: string
          description: Unique identifier for the plan
          example: plan_789
        learner_id:
          type: string
          description: Learner identifier
          example: 5df00a07-7391-4233-9896-a2ad86ad2b78
        subject:
          type: string
          enum:
          - mathematics
          - science
          - language_arts
          - social_studies
          - foreign_language
          description: Subject area
          example: mathematics
        activities:
          type: array
          items:
            $ref: '#/components/schemas/PlannedActivity'
        total_duration_minutes:
          type: integer
          description: Total duration of all activities
          example: 30
        created_at:
          type: string
          format: date-time
          description: When the plan was created
          example: '2025-09-13T00:14:43.325752+00:00'
        expires_at:
          type: string
          format: date-time
          description: When the plan expires
          example: '2025-09-13T00:14:43.325752+00:00'
        planner_version:
          type: string
          description: Version of the planner used
          example: '1.0'
    PlannedActivity:
      type: object
      properties:
        activity_id:
          type: string
          description: Unique identifier for the activity
          example: a742fc8f-46fb-4505-ad1d-93f0781553c0
        type:
          type: string
          enum:
          - lesson
          - practice
          - assessment
          - remediation
          - enrichment
          description: Type of learning activity
          example: lesson
        topic:
          $ref: '#/components/schemas/CourseworkTopic'
        estimated_duration_minutes:
          type: integer
          description: Estimated time to complete
          example: 15
        difficulty_adjustment:
          type: number
          minimum: 0.5
          maximum: 2.0
          description: Multiplier for base difficulty
          example: 1.0
        learning_objectives:
          type: array
          items:
            type: string
          description: Learning objectives for this activity
          example:
          - Understand basic fractions
          - Compare fraction sizes
        prerequisites_met:
          type: boolean
          description: Whether prerequisites are satisfied
          example: true
        rationale:
          type: string
          description: Explanation for why this activity was selected
          example: da929d4e-bf44-475d-ae67-6c4fae8620c8
    CourseworkTopic:
      type: object
      properties:
        topic_id:
          type: string
          description: Unique identifier for the topic
          example: 60551d21-63e7-4ce0-a380-2d6299313710
        name:
          type: string
          description: Human-readable topic name
          example: 7052f146-ec6a-48c3-9154-312c577acb2d
        subject:
          type: string
          enum:
          - mathematics
          - science
          - language_arts
          - social_studies
          - foreign_language
          description: Subject area
          example: mathematics
        grade_level:
          type: integer
          minimum: 1
          maximum: 12
          description: Target grade level
          example: 3
        prerequisites:
          type: array
          items:
            type: string
          description: Required prerequisite topics
          example:
          - topic_whole_numbers
        learning_objectives:
          type: array
          items:
            type: string
          description: Learning objectives for this topic
          example:
          - Identify fractions
          - Compare fractions
        estimated_duration_minutes:
          type: integer
          description: Estimated time to complete
          example: 20
        difficulty_level:
          type: integer
          minimum: 1
          maximum: 10
          description: Difficulty rating
          example: 3
    RuntimeRequest:
      type: object
      properties:
        runtime_id:
          type: string
          description: Unique identifier for the runtime
          example: a14c49a5-b95a-4a1a-87f5-974058f94a2c
        learner_id:
          type: string
          description: Learner identifier
          example: e7d237b4-4276-4213-9495-d14c8f53d266
        subject:
          type: string
          enum:
          - mathematics
          - science
          - language_arts
          - social_studies
          - foreign_language
          description: Subject area
          example: mathematics
        activity_plan:
          $ref: '#/components/schemas/ActivityPlan'
        gpu_required:
          type: boolean
          description: Whether GPU resources are required
          example: true
        memory_mb:
          type: integer
          description: Memory requirement in MB
          example: 2048
        cpu_cores:
          type: number
          description: CPU cores required
          example: 1.0
        max_runtime_minutes:
          type: integer
          description: Maximum runtime duration
          example: 120
        priority:
          type: integer
          minimum: 1
          maximum: 10
          description: Runtime priority level
          example: 5
    RuntimeStatusResponse:
      type: object
      properties:
        runtime_id:
          type: string
          description: Runtime identifier
          example: c655abc8-5868-468d-86a4-c15d54d85b20
        status:
          type: string
          enum:
          - pending
          - running
          - scaling
          - idle
          - terminating
          - terminated
          description: Current runtime status
          example: running
        metrics:
          $ref: '#/components/schemas/RuntimeMetrics'
        estimated_completion_minutes:
          type: integer
          nullable: true
          description: Estimated time to completion
          example: 15
        current_activity:
          type: string
          nullable: true
          description: Currently executing activity
          example: 4e176691-a8f7-40c2-a195-0fe931d3da16
    RuntimeMetrics:
      type: object
      properties:
        runtime_id:
          type: string
          description: Runtime identifier
          example: 5f47f2d1-6431-4fa7-89b2-f496bc8653b8
        gpu_queue_depth:
          type: integer
          description: Current GPU queue depth
          example: 5
        gpu_utilization_percent:
          type: number
          description: GPU utilization percentage
          example: 75.5
        memory_usage_mb:
          type: integer
          description: Current memory usage in MB
          example: 1024
        cpu_utilization_percent:
          type: number
          description: CPU utilization percentage
          example: 45.2
        active_learners:
          type: integer
          description: Number of active learners
          example: 1
        pending_requests:
          type: integer
          description: Number of pending requests
          example: 0
        last_activity_timestamp:
          type: string
          format: date-time
          description: Timestamp of last activity
          example: '2025-09-13T00:14:43.326757+00:00'
    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message
          example: 86e858db-857d-4ac4-bc43-36add5313906
tags:
- name: Health
  description: Service health monitoring
- name: Monitoring
  description: Metrics and performance monitoring
- name: Planner
  description: AI-powered activity planning
- name: Runtime
  description: Per-learner-subject runtime management
