# coding: utf-8

# flake8: noqa

"""
    Authentication Service API

    Core authentication and authorization service

    The version of the OpenAPI document: 1.0.0
    Contact: api-support@aivo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthenticationApi",
    "ProfileApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthResponse",
    "Error",
    "LoginRequest",
    "RefreshTokenRequest",
    "User",
    "ValidationError",
    "ValidationErrorValidationErrorsInner",
]

# import apis into sdk package
from aivo_sdk.api.authentication_api import AuthenticationApi as AuthenticationApi
from aivo_sdk.api.profile_api import ProfileApi as ProfileApi

# import ApiClient
from aivo_sdk.api_response import ApiResponse as ApiResponse
from aivo_sdk.api_client import ApiClient as ApiClient
from aivo_sdk.configuration import Configuration as Configuration
from aivo_sdk.exceptions import OpenApiException as OpenApiException
from aivo_sdk.exceptions import ApiTypeError as ApiTypeError
from aivo_sdk.exceptions import ApiValueError as ApiValueError
from aivo_sdk.exceptions import ApiKeyError as ApiKeyError
from aivo_sdk.exceptions import ApiAttributeError as ApiAttributeError
from aivo_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from aivo_sdk.models.auth_response import AuthResponse as AuthResponse
from aivo_sdk.models.error import Error as Error
from aivo_sdk.models.login_request import LoginRequest as LoginRequest
from aivo_sdk.models.refresh_token_request import RefreshTokenRequest as RefreshTokenRequest
from aivo_sdk.models.user import User as User
from aivo_sdk.models.validation_error import ValidationError as ValidationError
from aivo_sdk.models.validation_error_validation_errors_inner import ValidationErrorValidationErrorsInner as ValidationErrorValidationErrorsInner
