name: python-hygiene

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: python-hygiene-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hygiene:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit ruff

      - name: Ensure Ruff config in pyproject (line-length=100, py311)
        run: |
          python scripts/ensure_ruff_config.py --write || true
          # Show diff if any
          git status --porcelain
          git --no-pager diff --stat

      - name: Run pre-commit (fix whitespace/eol)
        run: |
          pre-commit run --all-files

      - name: Ruff lint (no fixes)
        run: |
          ruff check .

      - name: Ruff format check
        run: |
          ruff format --check .

      - name: Fail if changes were produced by hooks
        run: |
          if ! git diff --quiet; then
            echo "::error::Pre-commit hooks or Ruff would modify files. Run 'pre-commit run --all-files' and 'ruff check --fix .' locally."
            git --no-pager diff --stat
            exit 1
          fi
