/* tslint:disable */
/* eslint-disable */
/**
 * Payments & Billing API
 * Subscription billing and payment processing service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodCard
 */
export interface PaymentMethodCard {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodCard
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodCard
     */
    last4?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodCard
     */
    expMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodCard
     */
    expYear?: number;
}

/**
 * Check if a given object implements the PaymentMethodCard interface.
 */
export function instanceOfPaymentMethodCard(value: object): value is PaymentMethodCard {
    return true;
}

export function PaymentMethodCardFromJSON(json: any): PaymentMethodCard {
    return PaymentMethodCardFromJSONTyped(json, false);
}

export function PaymentMethodCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodCard {
    if (json == null) {
        return json;
    }
    return {
        
        'brand': json['brand'] == null ? undefined : json['brand'],
        'last4': json['last4'] == null ? undefined : json['last4'],
        'expMonth': json['expMonth'] == null ? undefined : json['expMonth'],
        'expYear': json['expYear'] == null ? undefined : json['expYear'],
    };
}

export function PaymentMethodCardToJSON(json: any): PaymentMethodCard {
    return PaymentMethodCardToJSONTyped(json, false);
}

export function PaymentMethodCardToJSONTyped(value?: PaymentMethodCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brand': value['brand'],
        'last4': value['last4'],
        'expMonth': value['expMonth'],
        'expYear': value['expYear'],
    };
}

