/* tslint:disable */
/* eslint-disable */
/**
 * Payments & Billing API
 * Subscription billing and payment processing service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@aivo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodBankAccount
 */
export interface PaymentMethodBankAccount {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodBankAccount
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodBankAccount
     */
    last4?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodBankAccount
     */
    accountType?: PaymentMethodBankAccountAccountTypeEnum;
}


/**
 * @export
 */
export const PaymentMethodBankAccountAccountTypeEnum = {
    Checking: 'checking',
    Savings: 'savings'
} as const;
export type PaymentMethodBankAccountAccountTypeEnum = typeof PaymentMethodBankAccountAccountTypeEnum[keyof typeof PaymentMethodBankAccountAccountTypeEnum];


/**
 * Check if a given object implements the PaymentMethodBankAccount interface.
 */
export function instanceOfPaymentMethodBankAccount(value: object): value is PaymentMethodBankAccount {
    return true;
}

export function PaymentMethodBankAccountFromJSON(json: any): PaymentMethodBankAccount {
    return PaymentMethodBankAccountFromJSONTyped(json, false);
}

export function PaymentMethodBankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodBankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'bankName': json['bankName'] == null ? undefined : json['bankName'],
        'last4': json['last4'] == null ? undefined : json['last4'],
        'accountType': json['accountType'] == null ? undefined : json['accountType'],
    };
}

export function PaymentMethodBankAccountToJSON(json: any): PaymentMethodBankAccount {
    return PaymentMethodBankAccountToJSONTyped(json, false);
}

export function PaymentMethodBankAccountToJSONTyped(value?: PaymentMethodBankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bankName': value['bankName'],
        'last4': value['last4'],
        'accountType': value['accountType'],
    };
}

